version: '3'
services:
  nginx:
    image: nginx
    links:
      - wikijs
    depends_on:
      - wikijs
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/letsencrypt
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3000:3000'
    expose:
      - '3000'
    environment:
      WIKI_ADMIN_EMAIL: technology@thirstie.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./.ssh:/var/wiki/.ssh
